name: Publish wiki
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      wiki: ${{ steps.filter.outputs.wiki }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            wiki:
              - 'wiki/**'
              - '.github/workflows/publish-wiki.yml'

  publish:
    needs: changes
    if: needs.changes.outputs.wiki == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@v5
        with:
          path: wiki
          commit-message: "docs: sync from main branch"
